name: build and test

on: 
  push:
  
  workflow_dispatch: 
    
jobs:
  build-test: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: checkout code
        uses: actions/checkout@v2
      - name: test
        run: |
          make test
          ./lab7_test < test_input > test_output
          CODECOV_TOKEN='c93bcfc7-ae03-44e7-85eb-66d4de48f0f6'
          bash <(curl -s https://codecov.io/bash)
