name: build and test

on: 
  push:
  
  workflow_dispatch: 
    
jobs:
  build-test: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: checkout code
        uses: actions/checkout@v2
      - name: test
        run: |
          make test
          ./lab7_test < test_input > test_output
