name: build-&-test
 
on:
  push: 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: build
        run: |
         .git/HEAD
         git checkout Lab1
         cd Res/
         make test
         ./test
          
